<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.*" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="3.*" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.*" />
    <PackageReference Include="AWSSDK.S3" Version="3.*" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.*" />
    <PackageReference Include="System.Net.Http.Json" Version="8.*" />
    <PackageReference Include="PdfPig" Version="0.1.*" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemanticSearch.Core\SemanticSearch.Core.csproj" />
  </ItemGroup>
</Project>
